
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: yayos_barber
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"  # Evita conflicto con Laragon
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
