# Generated by Django 5.1.4 on 2025-06-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_cliente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbero',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
