# Generated by Django 5.1.4 on 2025-06-12 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0003_quienessomos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='barbero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cita.barbero'),
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de comisión sobre el servicio', max_digits=5)),
                ('barbero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cita.barbero')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cita.cita')),
            ],
        ),
    ]
