# Generated by Django 5.1.4 on 2025-06-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0004_adminprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
