# Generated by Django 5.1.4 on 2025-09-24 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.horariodisponible'),
        ),
    ]
